name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
           echo "${{ secrets.DOCKER_PASSWD }}" | docker login -u "failure000" --password-stdin
           docker image build -t failure000/nodeapp:v1
           docker push failure000/nodeapp:v1
